### ISSUE TITLE
How to setup it ?

### ISSUE THREAD

**Issue by Romeus** [plumdog/django_migration_testcase#4] opened 2015-08-30 13:41 UTC
I have cloned it and try to run setup. This is the result:

/tmp/django_migration_testcase$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by plumdog** [comment] 2015-09-02 08:13
You should just be able to run:
```
python setup.py install
```
or, just install from pypi rather than cloning if you rather:
```
pip install django_migration_testcase
```

If you install from a clone, make sure you get the latest version. I recently merged #3 which fixed a bug where it wasn't installing correctly. Also, to actually use it, it needs to be within a Django project - it looks for some settings at import time (just because of the Django things it uses). However, you should be able to run the tests anyway, because they have their own test project.

Any further problems, just ask here.

**Comment by Romeus** [comment] 2015-09-03 13:43
Thank you, Andrew. Now it is installed and worked. But I have found that migration code runs twice. I added "print let's go" statement to function called from RunPython operation and this prints twice.

**Comment by Romeus** [comment] 2015-09-03 14:24
Let me clarify. I have seen that there is three methods who calls 'migration' command: setUp, tearDown and runMigration. I have these lines in my test class:
        user_1 = User.objects.create(username="user_1@test.com")
        user_2 = User.objects.create(username="user_2@test.com")
        user_3 = User.objects.create(username="user_3@test.com")

        print "Users: %s" % User.objects.all()

And there are no manipulations with scheme or data in my migration. There is no problem when it calls in setUp. But there are problem in tearDown. Users objects are empty.

**Comment by plumdog** [comment] 2015-09-04 07:41
Interesting. I guess that it is being called once as part of `setUp` or `tearDown`, as well as when `run_migration` is called. And if you're using `RunPython`, I assume that means you're using django's migrations, rather than south migrations?

**Comment by Romeus** [comment] 2015-09-04 07:45
Yes, I used django migrations. I have commented call migration in setUp and TearDown and migration works but I have found another error:
https://code.djangoproject.com/ticket/24282

But this error have no relation to your extension.

**Comment by plumdog** [comment] 2015-09-07 20:45
Hi - I've worked out why. Turns out that Django's default test runner runs all the migrations to setup the database for the first time.

If you have a test file that just looks like
```python
from django.test import TestCase
class EmptyTestCase(TestCase):
    pass
```
and have a migration that looks like
```python
from django.db import migrations
def forwards(apps, schema_editor):
    print '!go forwards!'

class Migration(migrations.Migration):
    operations = [migrations.RunPython(forwards)]
```
Then you'll get something like
```
❯ ./manage.py test 
Creating test database for alias 'default'...
!go forwards!

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
```
So based on that, I think that this is expected behaviour!
There are [ways of getting Django not to run migrations to build the database, and instead to just create the database from the current state of models](http://stackoverflow.com/a/25267435).
Let me know if you find something to the contrary, or if this is causing a problem in your case.

**Comment by plumdog** [comment] 2015-09-17 20:50
Hi - if you've got any more question, just ask. But for now I'll close the issue.

**Closed by plumdog** 2015-09-17 20:50 UTC
